### ISSUE TITLE
Reference data sources in different files.

### ISSUE THREAD

**Issue by piraz** [candango/firenado#171]
We need the ability to reference data sources in different files at the data source section in the firenado.yml config file.

The file will  contain a set of data sources items and will referenced by the file index:

```
data:
  sources:
    - name: session
      connector: redis
      # host: localhost
      # port: 6379
      # db: 0
    - file: data_sources.yml
```

The data_sources.yml file will have items like:

```
 - name: test
   connector: sqlalchemy
   url: mysql+pymysql://root:rootpass@localhost:3306/test
```
