### ISSUE TITLE
Add json session encoder to the project

### ISSUE THREAD

**Issue by piraz** [candango/firenado#295]
Also we need to effectively change the encoder type in the app conf file.

If user sets:

```
session:
  type: redis
  enabled: true
  encoder: json <--- this is not being set in the conf during the application load process
  data:
    source: session
``` 

The encoder will keep as pickle(the default one). The session encoder must  be changed as defined in the app config file.
