### ISSUE TITLE
Add future parameter to the sqlalchemy data source

### ISSUE THREAD

**Issue by piraz** [candango/firenado#354]
To be able to migrate the application to the 2.0 style it is necessary set the future as true while creating an engine.

At this ticket we're just add the parameter to the configuration:

```
data:
  sources:
    - name: storage
      connector: sqlalchemy
      url: postgresql+psycopg2://user:password@127.0.0.1:5432/database
      future: true
```

See:
 - https://docs.sqlalchemy.org/en/14/glossary.html#term-1
 - https://docs.sqlalchemy.org/en/14/changelog/migration_20.html
