### ISSUE TITLE
Move isolation_level to the root of a sqlalchemy data source configuration

### ISSUE THREAD

**Issue by piraz** [candango/firenado#447]
The isolation level use to be in the pool configuration of a sqlalchemy data source. Let's move it to the root.

Instead of:

```yaml
data:
  sources:
    - name: test
      connector: sqlalchemy
      url: mysql+pymysql://root@localhost:3306/test
      pool:
        - isolation_level: REPEATABLE READ
```
Place it at:

```yaml
data:
  sources:
    - name: test
      connector: sqlalchemy
      url: mysql+pymysql://root@localhost:3306/test
      isolation_level: REPEATABLE READ
```
