### ISSUE TITLE
Disable sqlalchemy connection_ping by default

### ISSUE THREAD

**Issue by piraz** [candango/firenado#452]
Let's didable sqlalchemy `connection_ping` by default. To enable use:

```yaml
data:
  sources:
    - name: test
      connector: sqlalchemy
      url: mysql+pymysql://root@localhost:3306/test
      ping: true
```
